### PR TITLE
If sources list file has default content, exit gracefully

### PR DESCRIPTION
**Pull request by rotu**
Fixes https://github.com/ros-tooling/setup-ros/issues/174

### CODE REVIEW

**Review by emersonknapp — APPROVED** [review]
Nice!

**Comment by rotu** [comment]
What’s my next step to get this merged in?

**Comment by rotu** [comment]
What’s my next step to get this merged in?

**Comment by emersonknapp** [comment]
Maybe we ping @nuclearsandwich @tfoote for review?

**Comment by nuclearsandwich** [comment]
My initial reaction was that invoking rosdep init in a script like

```
test -f /etc/ros/rosdep/sources.list.d/20-default.list || rosdep init
```

would be a reasonable way to get this feature without a code change but that script assumes the default path would never change and doesn't warn if the contents update so this has obvious advantages.

@rotu would you be interested in adding tests for the two reinitialization cases? (same content and changed content)

**Review by nuclearsandwich — CHANGES_REQUESTED** [review]
I think all this needs is tests and then we can merge it.

**Comment by rotu** [comment]
@nuclearsandwich Feel free to take over this PR

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich Feel free to take over this PR

Thanks, I'm not sure I'll get to it but if anyone wants to see this change merged open a PR with these changes and some tests and I'll review it.

**Pull request closed without merging**
