### PR TITLE
Elementary OS patch

### PR DESCRIPTION
**Pull request by georgepar**
A dead simple patch to make rosdep work in ElementaryOS

### CODE REVIEW

**Comment by georgepar** [comment]
Doh. Depends on [this patch](https://github.com/ros-infrastructure/rospkg/pull/84) I submitted in the rospkg project

**Comment by cottsay** [comment]
Note that `stdeb.cfg` and `setup.py` should eventually be updated to express the new version dependency when the `rospkg` patch is merged and released.

**Comment by tfoote** [comment]
The updated rospkg PR is https://github.com/ros-infrastructure/rospkg/pull/85

**Comment by georgepar** [comment]
Hey guys,

Can anyone tell me which version of rospkg should I define in `stdeb.cfg` and `setup.py` now that  os-infrastructure/rospkg#85 was merged to the upstream?

**Comment by wjwwood** [comment]
@georgepar probably `1.0.36`?

**Comment by dirk-thomas** [comment]
It is not in `1.0.36` which was released five days ago.

It is in `1.0.37` which was just released.

**Comment by georgepar** [comment]
Thanks. I also tried to squash the commits.

**Comment by tfoote** [comment]
I'd suggest retrying the squashing. There's still 6 commits with some of them empty.

**Pull request merged**
