### PR TITLE
Add Python 3.7 and 3.8 to test matrix

### PR DESCRIPTION
**Pull request by sloretz**
Mimicking ros-infrastructure/catkin_pkg#273

### CODE REVIEW

**Comment by jacobperron** [comment]
CI is failing because of `rospkg`. I believe a bug was introduced in https://github.com/ros-infrastructure/rospkg/pull/182.

**Comment by sloretz** [comment]
> CI is failing because of rospkg. I believe a bug was introduced in ros-infrastructure/rospkg#182.

Fix in https://github.com/ros-infrastructure/rospkg/pull/189

**Comment by sloretz** [comment]
Python 3.8 CI passes now that rospkg 1.2.3 is released.

One travis job on this pr fails with `[Errno 13] Permission denied: '/usr/local/man'`, but [it also fails on `master`](https://travis-ci.org/ros-infrastructure/rosdep/jobs/631834331?utm_medium=notification&utm_source=github_status) so it shouldn't block this PR.

**Comment by nuclearsandwich** [comment]
Accidentally closed without comment but Python 3.7 and 3.8 were added in #739.

**Pull request closed without merging**
