### PR TITLE
Added Zorin support

### PR DESCRIPTION
**Pull request by gstavrinos**
For this (https://github.com/ros-infrastructure/rosdep/issues/696) issue. Similar commit in https://github.com/ros-infrastructure/rospkg/pull/175.

### CODE REVIEW

**Review by tfoote — DISMISSED** [review]
This was failing CI because the necessary rospkg changes weren't released yet. They have been now in 1.2.0 to that end though please update the setup.py and stdeb to require at least 1.2.0 otherwise it will crash like the CI was doing. 

I've retriggered CI to test it against the new release of rospkg.

**Comment by gstavrinos** [comment]
Is there anything I should do in order for this to be merged?

**Comment by nuclearsandwich** [comment]
@gstavrinos I've opened https://github.com/gstavrinos/rosdep/pull/1 to resolve the merge conflicts here.

**Comment by gstavrinos** [comment]
@nuclearsandwich, Thanks for looking into this. I think I did all the required actions. Please hit me up if anything else is needed.

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
