### PR TITLE
fix quiet mode of debian installer

### PR DESCRIPTION
**Pull request by ipa-mdl**

### CODE REVIEW

**Comment by tfoote** [comment]
Good catch, I updated it for a slightly more compact implementation.

**Comment by ipa-mdl** [comment]
The same structure is used in `redhat.py`, but without the typo.
The test failure is unrelated.

**Comment by wjwwood** [comment]
@tfoote should I merge this then (you can feel free to merge it as well)? I don't have time to do a release right now. Though a rosdep release is something I should do soon, maybe just after the ROS 2 release.

**Comment by ipa-mdl** [comment]
> The failure mode for this is that it won't pass the quiet flags through if you use -y

The quiet flag was not passed at all.
This bug was present for 4 years, so a release is not urgent.

**Comment by 708yamaguchi** [comment]
@tfoote @wjwwood 
Could you please release `0.12.3` version of `rosdep`?
I have a problem that our `travis` fails because the travis log exceeds its maximum log length. (for example https://github.com/jsk-ros-pkg/jsk_robot/pull/963 and https://github.com/jsk-ros-pkg/jsk_robot/pull/969)
I think this issue will be solved if this commit is merged.

**Comment by ipa-mdl** [comment]
The last release is more than 7 months old..

**Comment by nuclearsandwich** [comment]
This pull request has been released in rosdep 0.13.0. Thanks for contributing!

**Pull request merged**
