### PR TITLE
add alias for Pop! OS

### PR DESCRIPTION
**Pull request by mikaelarguedas**
requires https://github.com/ros-infrastructure/rospkg/pull/199

(this will need a bump of the version of rospkg(-modules) once https://github.com/ros-infrastructure/rospkg/pull/199 is part of a release)

### CODE REVIEW

**Comment by emersonknapp** [comment]
@mikaelarguedas I'm not sure how to re-trigger the travis build, but force-pushing the commit with a new hash should do it

**Comment by mikaelarguedas** [comment]
@emersonknapp I believe this is still waiting for the dependant PR https://github.com/ros-infrastructure/rospkg/pull/199 to be released for this PR to pass CI

**Comment by emersonknapp** [comment]
Ohh - yeah I forgot that releases aren't automatic heh

**Comment by mikaelarguedas** [comment]
@tfoote dependencies have been updated to require the version of rospkg that has the Pop! OS detector

**Comment by mikaelarguedas** [comment]
@tfoote @nuclearsandwich Friendly ping

**Comment by mikaelarguedas** [comment]
friendly :bellhop_bell: is there anything blocking this ?

**Comment by tfoote** [comment]
No, sorry just vacation backlog.

**Pull request merged**
