### PR TITLE
Make fix-permissions work in an uninitialized state

### PR DESCRIPTION
**Pull request by spaghetti-**
Fixes https://github.com/ros-infrastructure/rosdep/issues/382

Tested on Ubuntu/OSX

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
Thanks for the patch.

Not sure we need to setup the proxy for fix-permissions.

The patch looks like it solves the problem. Could you possibly rewrite it to neither setup the proxy, nor call `check_for_sources_list_init(options.sources_cache_dir)` to avoid confusion later?

**Comment by spaghetti-** [comment]
@NikolausDemmel sure, done.

**Comment by NikolausDemmel** [comment]
lgtm :+1:

**Comment by tfoote** [comment]
Thanks for the patch and iteration.

**Pull request merged**
