### PR TITLE
Support --quiet option for pip

### PR DESCRIPTION
**Pull request by wkentaro**
On CI testing, the verbose output of pip install is annoying for me.

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
lgtm

**Comment by tfoote** [comment]
It would be cleaner to create the list and insert or append the quiet argument instead of duplicating the invocation line.

**Comment by wkentaro** [comment]
I have updated the commit.

**Comment by tfoote** [comment]
Thanks that's easier to extend (ala #450) Though you can keep the list comprehension with using the subcommand instead of using a for loop over the packages. Along the lines of:
```
In [1]: subcmd = ['foo', 'bar']
In [2]: pkgs = ['a', 'b', 'c']
In [3]: cmds = [subcmd + [p] for p in pkgs]
In [4]: cmds
Out[4]: [['foo', 'bar', 'a'], ['foo', 'bar', 'b'], ['foo', 'bar', 'c']]
```

**Comment by wkentaro** [comment]
Thanks. That's better.

**Comment by tfoote** [comment]
+1

**Comment by wjwwood** [comment]
Thanks!

**Pull request merged**
