### PR TITLE
fix REP3_TARGETS_URL

### PR DESCRIPTION
**Pull request by ipa-mdl**
Not sure if this is a temporary problem, but the old URL cannot be reached anymore:
> Error 503 Backend unavailable, connection timeout
> Backend unavailable, connection timeout

### CODE REVIEW

**Comment by ipa-mdl** [comment]
This problem breaks `rosdep update` for everyone.

**Comment by moriarty** [comment]
How long after this is merged will it take before the fix trickles down to the end users?

**Comment by subvertallchris** [comment]
Can we also get an ETA on when this will be merged?

For anyone who needs an immediate workaround and is _not_ using fuerte, you can comment out the `gbpdistro` line in `/etc/ros/rosdep/sources.list.d/20-default.list`. If you have a script that's automatic builds, here's a one-liner for you:

```
sudo sed -i '/gbpdistro/s/^/#/g' /etc/ros/rosdep/sources.list.d/20-default.list
```

Seems to work as far as I can tell.

**Comment by wjwwood** [comment]
It was just brought to my attention, I'm working on a release right now.

**Comment by wjwwood** [comment]
Ok, `0.15.1` is out and available from PyPi (pip) and packages.ros.org. I'm still syncing to the ros2 apt repository on packages.ros.org, but they should be getting updated very soon.

Please let me know if anyone is still having issues.

**Comment by wjwwood** [comment]
Thanks @ipa-mdl for the quick patch.

**Comment by zpzp307** [comment]
I am a newbie, i uninstalled the ros once , this time the installation is stuct in rosdep. error:

reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip end-of-life distro "ardent"
Add distro "bouncy"
Add distro "crystal"
Add distro "dashing"
Skip end-of-life distro "groovy"
Skip end-of-life distro "hydro"
Skip end-of-life distro "indigo"
Skip end-of-life distro "jade"
Add distro "kinetic"
ERROR: error loading sources list:
('The read operation timed out',)

**Comment by tfoote** [comment]
@zpzp307 Please don't ask questions on unrelated threads or ask things multiple times. Both are bad ettiquette please read through http://wiki.ros.org/Support

**Comment by zpzp307** [comment]
Sorry, I will follow the rules.


------------------ 原始邮件 ------------------
发件人: "Tully Foote"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 下午2:04
收件人: "ros-infrastructure/rosdep"<rosdep@noreply.github.com>;
抄送: "。。。"<3186677895@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [ros-infrastructure/rosdep] fix REP3_TARGETS_URL (#663)




@zpzp307 Please don't ask questions on unrelated threads or ask things multiple times. Both are bad ettiquette please read through http://wiki.ros.org/Support

**Pull request merged**
