### PR TITLE
fix get_view_key for meta-packages

### LINKED ISSUE #534: v0.11.7 breaks rosdep for meta-packages
Looks like #531 was not complete.

rosdep {keys, install} fails with 
```
MY_METAPACKAGE: Missing resource MY_METAPACKAGE
```

I will look into it again.

### PR DESCRIPTION
**Pull request by ipa-mdl**
fixes #534 

Should the stack keys get cached as well?

### CODE REVIEW

**Comment by ipa-mdl** [comment]
Should `get_loadable_views` return meta-packages?

**Comment by ipa-mdl** [comment]
in the last commit I have unified the handling of catkin packages. Feel free to drop it if you don't want to include this.

**Comment by k-okada** [comment]
great!!!, I found this solves our problem reporeted at https://github.com/ros-infrastructure/rosdep/issues/536

**Comment by ipa-mdl** [comment]
@tfoote, @wjwwood: Do you have time to review and release it?
This bug is affecting the CI jobs of many repositories, given they contain meta-packages.

**Comment by wjwwood** [comment]
@ipa-mdl yup, I plan to do it today. Just juggling a few things at the moment.

**Comment by wjwwood** [comment]
@ipa-mdl I was really hoping to update the tests introduced into #531 to cover this case before merging this, but given the priority I think I'll go ahead and merge/release having tested it locally.

If you have time to extend those tests I would really appreciate it. It would help us avoid this in the future.

**Comment by ipa-mdl** [comment]
Our CI tests are green again :D

> If you have time to extend those tests I would really appreciate it. It would help us avoid this in the future.

I will try to.
At least a test for `get_view_key` should be added.
It would be great to extend the CLI tests in test_rosdep_main.py

**Pull request merged**
